version: '2'
services:
    virtual_library_gateway-mongodb:
        image: mongo:3.4.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/virtual_library_gateway/mongodb/:/data/db/
